genome:
  id: hg38
  path: /media/lukasz/3bd84083-5cb2-415a-ad9c-4e453ce7cffd/MRumlova/genomes/hg38
  ext: .fa
rules:
  prepare_genome: true
  removing_adapters: true
  quality_filtering: true
  min_phred_score: '20'
  mapper: bowtie2
  remove_duplicates: true
  variant_caller: fasd-somatic
  annotate: true
programs:
  path: /media/lukasz/3bd84083-5cb2-415a-ad9c-4e453ce7cffd/MRumlova/programs/
samples:
  ids:
  - SRR7501654
  - SRR7501665
  suffix: _
  path: fastq/
  ext: .fastq

